[package]
name = "hellometrics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
opentelemetry = { path = "../opentelemetry/" }
opentelemetry-sdk = {path = "../opentelemetry-sdk/" }
